services:
  app:
    container_name: prreviewer_service
    image: prreviewer-service:latest
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: pr_reviewer_db_postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${DATASOURCE_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "psql -U ${DATASOURCE_USERNAME} -d ${DATASOURCE_NAME} -c 'SELECT 1'" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: