services:
  app:
    container_name: prreviewer_service
    image: prreviewer-service:latest
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL:-jdbc:postgresql://db:5432/pr_reviewer_db}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME:-noleg}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD:-root}
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: pr_reviewer_db_postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME:-noleg}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD:-root}
      POSTGRES_DB: ${DATASOURCE_NAME:-pr_reviewer_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "psql -U ${DATASOURCE_USERNAME:-noleg} -d ${DATASOURCE_NAME:-pr_reviewer_db} -c 'SELECT 1'" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: