spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://db:5432/pr_reviewer_db}
    username: ${DATASOURCE_USERNAME:noleg}
    password: ${DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  config:
    import: optional:file:.env[.properties]